version: "3"
services:
  redis:
   image: "redis"
   expose:
    - 6379
   ports:
    - "6379:6379"

  node:
    links:
      - redis
    environment:
    image: "node:8"
    user: "node"
    environment:
      - NODE_ENV=development
    build: .
    volumes:
      - .:/home/node/app
    ports:
      - '3000:3000'
    command: "yarn start"
    depends_on:
      - redis
